name: lector
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  http: ^1.5.0
  cloud_firestore: ^6.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_card_swiper: ^7.1.0
  flutter_svg: ^2.2.1
  flutter_dotenv: ^6.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/data/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#4A2C2A"
  image: "assets/icon/splash_icon.png"
  android_12:
    color: "#4A2C2A"
    image: "assets/icon/splash_icon.png"