name: lector
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  http: ^1.5.0
  cloud_firestore: ^6.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true # Android için ikon oluştur
  ios: true # iOS için ikon oluştur
  image_path: "assets/icon/icon.png" # İkonumuzun yolu
  min_sdk_android: 21 # a splash screen background color.
  remove_alpha_ios: true

# Bu satırın dosyanın en solunda olduğundan emin ol
flutter_native_splash:
  color: "#4A2C2A" # Koyu kahverengi arka plan rengi (HEX kodu)
  # Veya istersen resim (arka plan görseli) de kullanabilirsin:
  # background_image: "assets/splash_background.png" 
  image: "assets/icon/splash_icon.png" # İkonumuzun yolu (şeffaf PNG olmalı)
  # Android 12 ve sonrası için de splash screen ayarlaması
  android_12:
    color: "#4A2C2A"
    image: "assets/icon/splash_icon.png"